### ISSUE TITLE
Remove vouch from docker-compose

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon-distributed-validator-cluster#101]
## Problem to be solved

We need to remove 2 vouch services from docker-compose.yml because block proposal duty of vouch is incompatible with DVT. This will cause missed block proposals in all the cluster run using this repo.

## Proposed Solution

Replace both vouch VCs with one lighthouse and one teku VC.

**Comment by xenowits** [comment]
@dB2510 we should also create a ticket so that we don't forget to add back these vouch containers by the next release

**Comment by dB2510** [comment]
Fixed by #104
