### ISSUE TITLE
Update local Grafana Dashboard

### ISSUE THREAD

**Issue by redecvi** [ObolNetwork/charon-distributed-validator-cluster#141]
# 🎯 Problem to be solved

We want to update the locally deployed Grafana Dashboard.

# 🛠️ Proposed solution

- Re-arrange the panels and think about adding/removing some
- Add descriptions/documentations to unclear visualizations

# 👐 Additional acceptance criteria

Should be signed off by relevant stakeholders

**Comment by anadi2311** [comment]
@LukeHackett12 should we delete this as well and add overview dashboard here too?

**Comment by anadi2311** [comment]
closing as it is covered in #98
