### ISSUE TITLE
Add Vouch validator client

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon-distributed-validator-cluster#24]
## Problem to solve

Charon states it supports Vouch validator client. But this hasn't been tested or confirmed yet. This repo also only had teku and lighthouse.

## Proposed solution:

- Add Vouch as VC for node3.
- A single node Vouch is all that is required (not multi-node). 
- First prize is implementing it the same as teku (without a folder or run script), just a docker-compose service.
- Remember to configure network as auto, since charon can connect to prater/gnosis/kiln/simnet/devnet.
- Remember to load the keys on startup.
- If this is not trival, like lighthouse, a folder and run script can be added.
- Try to keep everything to the absolute minimum

**Comment by OisinKyne** [comment]
Finish this PR https://github.com/ObolNetwork/charon-distributed-validator-cluster/pull/35
