### ISSUE TITLE
Create a `charon-node-docker-compose` repo.

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-cluster#36]
## Problem to be Solved

We want a separate repo for people to start single nodes in a distributed cluster

## Proposed Solution

Create a fork of this repo called `charon-node-docker-compose`, and rename this one to `charon-cluster-docker-compose`. 

In charon-node, we should have a docker-compose file that brings up one of a few choices of beacon nodes, and depends on the `kiln.themerge.dev` eth1 rpc (or our geth kiln node if its still running). Its readmes should explain creating a cluster definition file, and using it in a charon dkg ceremony, before loading it into a validator. 

## Out of scope

More than one Consensus Engine not required for  this ticket.

**Comment by dB2510** [comment]
This one is done!
