### ISSUE TITLE
Add nimbus validator support

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-cluster#67]
## Problem to be solved

We want to support all validator client implementations

## Proposed solution

Figure out a status update on status's plans for an independent VC implementation. If it exists, work on making a dockerfile for it that allows it to run in this repo. 

## Out of scope

Supporting a nimbus beacon node

**Comment by Battenfield** [comment]
Nimbus team potentially taking this on

**Comment by xenowits** [comment]
https://nimbus.guide/validator-client.html

**Comment by xenowits** [comment]
Nimbus VC fully integrated 🎉

**Comment by xenowits** [comment]
Nimbus VC fully integrated 🎉
