### ISSUE TITLE
Add local EL+CL

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon-distributed-validator-cluster#69]
## Problem to be solved

If we go to 6 VCs, that's a hell of a lot of requests to be firing at infura, which isn't all that great anyways. 

## Proposed solution

Add an EL+CL pair of containers that are not geth + lighthouse. Ideally have fast sync enabled on the CL side so it doesn't take long to get started and healthy.

**Comment by xenowits** [comment]
@OisinKyne Just one pair of container for all 6 charon nodes, right?

**Comment by xenowits** [comment]
I'm trying to do a pair of Nethermind + Nimbus. Let's see how it goes
