### ISSUE TITLE
Fix issues with nimbus BN

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon-distributed-validator-cluster#81]
## Problem to be solved

The nimbus beacon node has some issues:
* The `sync-distance` keeps on increasing instead of decreasing.
* The latency for most of the endpoints is high.

## Proposed solution

Spike into the issue and dig into the root cause and fix the issue. Ensure the whole cluster is working properly including synced nethermind.

**Comment by OisinKyne** [comment]
Is this issue still occuring @xenowits? Should we allocate this bug a severity level? If this repo is broken without this fix we should flag that.

**Comment by OisinKyne** [comment]
Actually, if I remember correctly, I think Jim McDonald said that the Nimbus REST API runs on a single thread, so maybe that is part of the latency issues. This if true would definitely be unfriendly for this repo that has 6 VCs/DVCs calling it simultaneously

**Comment by xenowits** [comment]
> Actually, if I remember correctly, I think Jim McDonald said that the Nimbus REST API runs on a single thread, so maybe that is part of the latency issues. This if true would definitely be unfriendly for this repo that has 6 VCs/DVCs calling it simultaneously

Yeah probably, will dig into more specific details. But, yeah it's probably too much to have 6 VCs asking for data from one single-threaded nimbus BN process

**Comment by xenowits** [comment]
Turned out it was not a performance issue but the real issue was docker needs more resource capabilities. Checkpoint sync works just fine
